Tshop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path
from .views import index,signup, cart, orders, signout, show_product, add_to_cart, checkout
from .views import validatePayment, OrderListView, login_required, LoginView, clear_cart

urlpatterns = [
   path('', index, name='homepage'),
   path('signup/', signup),
   path('cart/', cart, name='cartpage'),
   path('clear_cart/', clear_cart, name='clear_cart'),
  
   path('login/', LoginView.as_view(), name='login'),
   path('logout/', signout),
   path('product/<str:slug>', show_product),
   path('addtocart/<str:slug>/<str:size>', add_to_cart),
   path('checkout/', checkout),
   path('validate_payment/', validatePayment),
   path('orders/' , orders , name='orders' ), 
  


   
]

shop/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime




class TshirtProperty(models.Model):
    title = models.CharField(max_length=50, null=False)
    slug = models.CharField(max_length=200 , null=True  ,unique=False , default="")

    def __str__(self):
        return self.title

    class meta:
        abstract = True
# Create your models here.


class Occasion(TshirtProperty):
    pass


class IdealFor(TshirtProperty):
    pass


class NeckType(TshirtProperty):
    pass


class Sleeve(TshirtProperty):
    pass


class Brand(TshirtProperty):
    pass


class Color(TshirtProperty):
    pass


class Tshirt(models.Model):
    name = models.CharField(max_length=50, null=False)
    slug = models.CharField(max_length=200 , null=False  ,unique=True, default=" ")
    description = models.CharField(max_length=500, null=True)
    discount = models.IntegerField(default=0)
    image = models.ImageField(upload_to='upload/images/', null=False)
    ocassion = models.ForeignKey(Occasion, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    ideal_for = models.ForeignKey(IdealFor, on_delete=models.CASCADE)
    sleeve = models.ForeignKey(Sleeve, on_delete=models.CASCADE)
    neck_type = models.ForeignKey(NeckType, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    


    def __str__(self):
        return self.name

    @staticmethod
    def get_all_product():
        return Tshirt.objects.all()


class SizeVariant(models.Model):
    SIZES = (
        ('S', 'Small'),
        ('M', 'Medium'),
        ('L', 'Large'),
        ('XL', 'Extra Large'),
        ('XXL', 'Extra Extra Large')
    )

    price = models.IntegerField(null=False, default=0)
    tshirt = models.ForeignKey(Tshirt, on_delete=models.CASCADE)
    size = models.CharField(choices=SIZES, max_length=5)

    def __str__(self):
        return f'{self.size}'


class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    password = models.CharField(max_length=50)

    def register(self):
        self.save()

    def ifExists(self):
        if Customer.objects.filter(email=self.email):
            return True
        else:
            return False

    @staticmethod
    def get_customer_by_email(email):
        try:
            return Customer.objects.get(email=email)
        except:
            return False

class Cart(models.Model):
    sizeVariant = models.ForeignKey(SizeVariant, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Order(models.Model):
    orderStatus = (
        ('PENDING', 'Pending'),
        ('PLACED', 'Placed'),
        ('CANCELED', 'Canceled'),
        ('COMPLETED', 'Completed'),
    )

    method = (
        ('COD', 'Cod'),
        ('ONLINE', 'Online'),
        
    )
    order_status = models.CharField(max_length=15 , choices=orderStatus)
    payment_method = models.CharField(max_length=15 , choices=method)
    shipping_address = models.CharField(max_length=100  , null = False)
    phone = models.CharField(max_length=10 , null=False )
    user = models.ForeignKey(User , on_delete = models.CASCADE)
    total = models.IntegerField(null=False)
    date = models.DateTimeField(null= False , auto_now_add=True)

    
class OrderItem(models.Model):
    order = models.ForeignKey(Order , on_delete = models.CASCADE)
    tshirt = models.ForeignKey(Tshirt , on_delete = models.CASCADE)
    size = models.ForeignKey(SizeVariant , on_delete = models.CASCADE)
    quantity = models.IntegerField(null=False) 
    price = models.IntegerField(null=False) 
    date = models.DateTimeField(null= False , auto_now_add=True)


class Payment(models.Model):
    order = models.ForeignKey(Order , on_delete = models.CASCADE)
    date = models.DateTimeField( auto_now_add=True)
    payment_status = models.CharField(max_length=15 , default='FAILED')
    payment_id = models.CharField(max_length=60)
    payment_request_id = models.CharField(max_length=100 , unique=True , null=False)
    



    
    

shop/forms/authform.py
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class CustomerAuthForm(AuthenticationForm):
    username = forms.EmailField(required=True , label="Email")

class CustomerCreationForm(UserCreationForm):
    
    username = forms.EmailField(required=True , label="Email" )
    first_name = forms.CharField(required=True , label="First Name")
    last_name = forms.CharField(required=True , label="Last Name")
    class Meta:
        model = User
        fields = ['username' ,'first_name' , "last_name" ]

    def clean_first_name(self):
        value = self.cleaned_data.get('first_name')
        if len(value.strip()) < 4 :
            raise ValidationError("First Name must be 4 char long...")
        return value.strip()
    
    def clean_last_name(self):
        value = self.cleaned_data.get('last_name')
        if len(value.strip()) < 4 :
            raise ValidationError("Last Name must be 4 char long...")
        return value.strip()

shop/forms/checkout_form.py
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from shop.models import Order

class CheckForm(forms.ModelForm):
    class Meta:
        model=Order
        fields = ['shipping_address' , 'phone' , 'payment_method']

shop/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.hashers import make_password, check_password
from shop.models import Customer, Tshirt, SizeVariant, Cart

from shop.forms.authform import CustomerCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login as loginuser, logout
from shop.models import Tshirt, SizeVariant, OrderItem, Order, Color, Payment, Occasion, Brand, Sleeve, NeckType, IdealFor
from math import floor
from shop.templatetags.tshirt_tags import min_price, sale_price
from shop.forms.checkout_form import CheckForm
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView

from django.core.paginator import Paginator
from urllib.parse import urlencode

from django.views.generic.base import View

from .forms.authform import CustomerAuthForm



from django.shortcuts import render, HttpResponse, redirect
from django.shortcuts import render, HttpResponse, redirect

from instamojo_wrapper import Instamojo
API_KEY="test_8ae61cb145b7edb37b01806374c"
AUTH_TOKEN="test_0a1a23705c1024395442cad8c43"
API = Instamojo(api_key=API_KEY, auth_token=AUTH_TOKEN, endpoint='https://test.instamojo.com/api/1.1/')


# Create your views here.
class LoginView(View):  
    def get(self , request):
        form = CustomerAuthForm()
        print('LOGIN VIEW CLASS')
        next_page = request.GET.get('next')
        if next_page is not None:
            request.session['next_page'] = next_page
        return render(request,
                      template_name='login.html',
                      context={'form': form})

    def post(self , request):
        add = request.session.get('plusItem')
        form = CustomerAuthForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                loginuser(request, user)

                session_cart = request.session.get('cart')
                if session_cart is None:
                    session_cart = []
                else:
                    for c in session_cart:
                        size = c.get('size')
                        tshirt_id = c.get('tshirt')
            
                        quantity = c.get('quantity')+1
                        cart_obj = Cart()
                        cart_obj.sizeVariant = SizeVariant.objects.get(
                            size=size, tshirt=tshirt_id)
                        cart_obj.quantity = quantity
                        cart_obj.user = user
                        cart_obj.save()

                # { size , tshirt , quantiti }
                cart = Cart.objects.filter(user=user)
                session_cart = []
                for c in cart:
                    obj = {
                        'size': c.sizeVariant.size,
                        'tshirt': c.sizeVariant.tshirt.id,
                        'quantity': c.quantity
                    }
                    session_cart.append(obj)

                request.session['cart'] = session_cart
                next_page = request.session.get('next_page')
                if next_page is None:
                    next_page = 'homepage'
                return redirect(next_page)
        else:
            return render(request,
                          template_name='login.html',
                          context={'form': form})


def add_cart_to_database(user, size, tshirt):
    size = SizeVariant.objects.get(size=size, tshirt=tshirt)
    existing = Cart.objects.filter(user=user, sizeVariant=size)

    if len(existing) > 0:
        obj = existing[0]
        obj.quantity = obj.quantity + 1
        obj.save()

    else:
        c = Cart()
        c.user = user
        c.sizeVariant = size
        c.quantity = 1
        c.save()

def add_cart_for_anom_user(cart, size, tshirt):
    flag = True
    for cart_obj in cart:
        t_id = cart_obj.get('tshirt')
        size_short = cart_obj.get('size')
        if t_id == tshirt.id and size == size_short:
            flag = False
            cart_obj['quantity'] = cart_obj['quantity'] + 1

    if flag:
        cart_obj = {'tshirt': tshirt.id, 'size': size, 'quantity': 1}
        cart.append(cart_obj)

def add_to_cart(request,slug,size):
    add = request.session.get('plusItem')
    user = None
    if request.user.is_authenticated:
        user = request.user

    cart = request.session.get('cart')
   
    if cart is None:
        cart=[]

    tshirt = Tshirt.objects.get(slug=slug) 
    request.session['cart']= cart
    

    add_cart_for_anom_user(cart, size, tshirt)
        
    if user is not None:
        add_cart_to_database(user, size, tshirt)
       
        
    request.session['cart']= cart 
    return_url = request.GET.get('return_url')
    return redirect (return_url)

def show_product(request, slug):
    tshirt = Tshirt.objects.get(slug=slug)
    size = request.GET.get('size')
    active_size = size

    if size is None:
        size = tshirt.sizevariant_set.all().order_by('price').first()
    
    size = tshirt.sizevariant_set.get(size=size)  
    size_price = floor(size.price)
    sell_price = size_price - (size_price * (tshirt.discount/100))
    sell_price = floor(sell_price)

    context = {
        'tshirt': tshirt,
        'price': sell_price,
        'size_price': size_price,
        'active_size': size
        
        
        

    }

    print(size)
    return render(request, template_name='product_details.html', context=context)


def index(request):
    query = request.GET
    tshirts = []
    tshirts = Tshirt.objects.all()

    brand = query.get('brand')
    neckType = query.get('necktype')
    color = query.get('color')
    idealFor = query.get('idealfor')
    sleeve = query.get('sleeve')
    page = query.get('page')


    if(page is None or page == ''):
        page = 1

    if brand != '' and brand is not None:
        tshirts = tshirts.filter(brand__slug=brand)
    if neckType != '' and neckType is not None:
        tshirts = tshirts.filter(neck_type__slug=neckType)
    if color != '' and color is not None:
        tshirts = tshirts.filter(color__slug=color)
    if sleeve != '' and sleeve is not None:
        tshirts = tshirts.filter(sleeve__slug=sleeve)
    if idealFor != '' and idealFor is not None:
        tshirts = tshirts.filter(ideal_for__slug=idealFor)

    occasion = Occasion.objects.all()
    brands =  Brand.objects.all()
    idealFor =  IdealFor.objects.all()
    sleeves =  Sleeve.objects.all()
    neckType =  NeckType.objects.all()
    colors =  Color.objects.all()

    cart = request.session.get('cart')

    paginator = Paginator(tshirts, 3)
    page_object = paginator.get_page(page)

    query = request.GET.copy()
    query['page'] = ''
    pageurl = urlencode(query)
    

    context = {
        'page_object': page_object,
        'occasions': occasion,
        'brands': brands,
        'idealFor': idealFor,
        'sleeves': sleeves,
        'neckType': neckType,
        'colors': colors,
        'pageurl' : pageurl

    }
    return render(request, 'index.html', context=context)


def cart(request):
    cart = request.session.get('cart')
    add = request.session.get('plusItem')
    if cart is None:
        cart = []
    for c in cart:
        tshirt_id = c.get('tshirt')
        tshirt = Tshirt.objects.get(id=tshirt_id)
        c['size'] = SizeVariant.objects.get(tshirt= tshirt_id , size= c['size'])
        c['tshirt']= tshirt
    print(cart)
    return render(request, 'cart.html', context={'cart': cart})

@login_required(login_url='/login/')
def orders(request):
    user = request.user
    orders = Order.objects.filter(user=user).order_by('-date').exclude(order_status='PENDING')
    context = {
        'orders' : orders
    }
    return render(request, 'orders.html', context=context)


def signup(request):
    if (request.method is 'GET'):
        form = CustomerCreationForm()

        context = {
            "form": form
        }
        return render(request, 'signup.html', context=context)

    else:
        form = CustomerCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.email = user.username
            user.save()
            print(user)
            return redirect('login')

            context = {
                "form": form
            }

        context = {
            "form": form
        }
        return render(request, 'signup.html', context=context)


def signout(request):
    logout(request)
    return redirect('homepage')

def cal_total_payable_amount(cart):
    total = 0
    for c in cart:
        discount =c.get('tshirt').discount
        price = c.get('size').price
        sale_price = floor(price-(price * (discount/100)))
        total_of_single_product = sale_price * c.get('quantity')
        total = total + total_of_single_product
        
    return total

@login_required(login_url='/login/')
def checkout(request):
    if request.method == 'GET':
        form = CheckForm()
        cart = request.session.get('cart')
        if cart is None:
            cart = []

        for c in cart:
            size_str = c.get('size')
            tshirt_id = c.get('tshirt')
            size_obj = SizeVariant.objects.get(size=size_str, tshirt=tshirt_id)
            c['size'] = size_obj
            c['tshirt'] = size_obj.tshirt

        print(cart)

        return render(request, 'checkout.html', {
            "form": form,
            'cart': cart
        })
    else:
        # post request
        form = CheckForm(request.POST)
        user = None
        if request.user.is_authenticated:
            user = request.user
        if form.is_valid():
            # payment
            cart = request.session.get('cart')
            if cart is None:

shop/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <title>welcome to demoShop!</title>

  <style>
    .display-5 {
      font-size: 30px;
      font-weight: 300;
    }
  </style>
</head>

<body>

  <!-- Navbar-->

  <nav class="navbar navbar-expand-lg navbar-light bg-light">



    <a class="navbar-brand" href="/">Coding Dream</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Store <span class="sr-only">(current)</span></a>
        </li>
      </ul>

      <ul class="navbar-nav my-2 my-lg-0">

        <li class="nav-item ">
          <a class="nav-link" href="/cart">Cart<span class="badge badge-info">{{request.session.cart| length}} </span><span class="sr-only">(current)</span></a>
        </li>
        {% if request.user.is_authenticated%}

        <li class="nav-item ">
          <a class="nav-link" href="/orders">Order <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item ">
          <a class="nav-link" href="/logout">Log out <span class="sr-only">(current)</span></a>
        </li>


        {%else%}




        <li class="nav-item ">
          <a class="nav-link" href="/login">Login <span class="sr-only">(current)</span></a>
        </li>


        <li class="nav-item ">
          <a class="nav-link" href="/signup">Signup <span class="sr-only">(current)</span></a>
        </li>

        {%endif%}


      </ul>



    </div>
  </nav>

  {% block content %} {%endblock%}






  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

  <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>

shop/templates/cart.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% block content %}

<div class="container">
    <div>
        <table class="table table-hover table-stripped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Image</th>
                    <th>Tshirt</th>
                    <th>Size</th>
                    <th>Price</th>
                    <th>Discount</th>
                    <th>Sale Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Add More</th>
                    <th>Remove</th>
                </tr>
            </thead>

            <tbody>
                {% for c in cart %}

                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><img height="70px" class="img rounded-circle" src='{{ c.tshirt.image.url }}'/></td>
                        <td>{{ c.tshirt.name }}</td>
                        <td>{{c.size.size}}</td>
                        <td>{{c.size.price|rupee}}</td>
                        <td>{{c.tshirt.discount}}%</td>
                        <td>{% clc_sale_price c.size.price c.tshirt.discount as sale_price %} {{sale_price|rupee}}</td>
                        <td>{{c.quantity}}</td>
                        <td>{% multiply c.quantity sale_price as total %}{{total|rupee}}</td>
                        <td><a class="btn btn-outline-dark">+</a></td>
                        <td><button class="btn btn-outline-dark">-</button></td>
                    </tr>

                {% endfor %}


                <tfoot>
                    <tr>
                        <th colspan="3"></th>
                        <th colspan="5">Payable Amount</th>
                        <th>{{ cart|cal_total_payable_amount|rupee }}</th>
                    </tr>
                    <tr>
                        <th colspan="7"></th>
                        <th colspan="2"><a href="/checkout"  class="btn btn-outline-dark">Continue to Checkout</a></th>
                    </tr>
                    <tr>
                        <th colspan="7"></th>
                        <th colspan="2"><a href="/clear_cart"  class="btn btn-outline-dark">Clear Cart</a></th>
                    </tr>
                </tfoot>
            </tbody>
        </table>
        
    </div>
</div>

{% endblock %}

shop/templates/checkout.html
{{% extends "./base.html" %}
{% load crispy_forms_tags %}
{% load tshirt_tags %}
{%block content%}
<div class="container">
    <div class="p-2">
        <div class="display-5">Checkout Page</div>
        <hr>
        <div class="row">
            <div class="col-lg-5 border rounded p-3">
                <form action="/checkout/" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <hr>
                    <div class="form-group">
                            <input type="submit" value="CheckOut" class="btn btn-outline-dark">
                    </div>
                </form>
            </div>

            <div class="col">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Tshirt</th>
                            <th>Size</th>
                            <th>Price After Dis.</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in cart %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{c.size.tshirt.name}}</td>
                                <td>{{c.size.size}}</td>
                                <td>{% clc_sale_price c.size.price c.size.tshirt.discount as result %}{{result|rupee}}</td>
                            </tr>
                        {%endfor%}
                    </tbody>
                </table>

                <hr>
                <div>
                    <div class="display-5 alert">Total Payable Amount : {{cart|cal_total_payable_amount|rupee}}</div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

shop/templates/login.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{%block content%}
<div class="col-lg-4 mx-auto border rounded p-3 mt-4">

    <form action="/login/" method="POST">
        {% csrf_token %}
        
        <div class="text-center">
            <h2 class="display-4">Login Here</h2>
        
            <img height="90" src="http://localhost:8000/image/download/upload/images/sports_tee.jpg">
            <hr>
        
        </div>
        {{form|crispy}}
    
        <div class="form-group">
          <label for=""></label>
          <input type="submit" name=""  value= "Log In" id="" class="btn btn-info" placeholder="" aria-describedby="helpId">
          
        </div>

    </form>
   

</div>

{%endblock%}

shop/templates/order.html
{%extends 'base.html'%}

{%block content%}


{%endblock%}

shop/templates/orders.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% load orders_tags %}

{%block content%}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Items</th>
                <th>Status</th>

            </tr>
        </thead>

        <tbody>
            {% for order in orders %}
            <tr>
                <td>{{forloop.counter}}</td>
                <td>{{order.date|date}}</td>
                <td>
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Image</th>
                                <th>Tshirt</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>

                        <tbody>
                            {% for oi in order.orderitem_set.all%}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td><img height="60px" class="border" src="{{oi.tshirt.image.url}}" alt=""></td>
                                <td>{{oi.tshirt.name}}</td>
                                <td>{{oi.price|rupee}}</td>
                                <td>{{oi.quantity}}</td>
                                <td>{% multiply oi.quantity oi.price as result %}{{result|rupee}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </td>

                <td>
                  
                    <span class="badge badge-{% get_order_status_class order.order_status %}">{{order.order_status}}</span>
                    
                    
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
      <nav aria-label="Page navigation" class="mt-2">
        <ul class="pagination justify-content-end">
          
          
          {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?{{pageurl}}1">&laquo; first</a></li>
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
          </li>
          {% endif %}

          <li class="page-item">
            <a class="page-link" href="">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
          </li>


          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
          </li>
         <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
         </li>
          {% endif %}
          
        </ul>
      </nav>


</div>
{% endblock %}

shop/templates/payment_failed.html
{% extends "./base.html" %}

{%block content%}
        <br>
        <br>
    <div class="jumbotron container p-2 alert alert-danger text-center">
        <h1 class="display-4">Payment Failed</h1>
        <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta incidunt a quibusdam quos nulla sit sunt saepe, animi fugiat provident obcaecati dolores perferendis assumenda ducimus veritatis minima eos tenetur. Illum!</p>
        <hr class="my-4">
        <p>your payemnt failed ..</p>
    </div>

{% endblock %}

shop/templates/payment_success.html
{% extends "./base.html" %}
{% load tshirt_tags %}
{% block content %}
Success

{%endblock%}

shop/templates/product_details.html
{% extends 'base.html'%}
{%load tshirt_tags%}
{% block content%}



<div class="container">
    <div class="row" >
        <div class="col">
            <div class="p-4 m-3 w-75 h-75">
                <img src="{{tshirt.image.url}}" , class='img-fluid' alt="">
            </div>

        </div>

        <div class="col border p-3 m-2">
            <div class="border" >
                <div class="display-4">{{tshirt.name}}</div>
            </div>
            <hr>
            <div>
                <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Cumque consectetur nobis, nesciunt quaerat
                    numquam, et laudantium facilis placeat dolor non, eveniet sit iure asperiores? Soluta quaerat culpa
                    ea
                    ducimus laborum!</p>
            </div>

            <div class="row ">
                <div class="col"> <label for="">select size</label>
                    

                    <div class="row">
                        {%for size in  tshirt.sizevariant_set.all%}

                        <div class="col">
                            <a href="/product/{{tshirt.slug}}?size={{size.size}}" ,class="btn btn-block btn-{%get_active_button active_size size%}  ">
                             {{size}}
                            </a>
                        </div>

                        {%endfor%}

                    </div>
                    <br>
                    <div class="display-5 badge badge-info">
                        Save: {{tshirt.discount}}%

                    </div>
                </div>
                <div class='col rounded mt-3'>
                    <div>
                    <div class="p-3">
                        <span><del class="text-danger">{{size_price|rupee}}</del></span>
                        &nbsp;
                        <span>{{price|rupee}}</span>
                    </div>
                </div>
                    <a href="/addtocart/{{tshirt.slug}}/{{active_size.size}}?return_url={{request.get_full_path}}", class="btn btn-outline-dark btn-block">Add To Cart</a>

                
                    <a href="/checkout", class="btn btn-outline-dark btn-block">Buy Now</a>
                        
                    
                </div>
                

            </div>

        </div>



    </div>
</div>
{%endblock%}